// patch_web_canvaskit.js — force the Flutter web loader to fetch CanvasKit
// from the LOCAL build (build/web/canvaskit/) instead of the gstatic CDN.
//
// Why: flutter_bootstrap.js (generated by `flutter build web`) passes no
// loader config, so the loader falls back to
// https://www.gstatic.com/flutter-canvaskit/<engine> — which is blocked in
// mainland China. Without a VPN the engine silently never boots (black
// screen, no error). The local canvaskit files ship with the build anyway.
//
// Run after every web build:
//   node tools/patch_web_canvaskit.js
'use strict';
const fs = require('fs');

const file = 'build/web/flutter_bootstrap.js';
let s = fs.readFileSync(file, 'utf8');

const oldLoad = '_flutter.loader.load({';
if (!s.includes(oldLoad)) {
  console.error('patch target not found in', file);
  process.exit(1);
}
if (s.includes('config:{canvasKitBaseUrl')) {
  console.log('already patched');
  process.exit(0);
}
s = s.replace(
  oldLoad,
  '_flutter.loader.load({config:{canvasKitBaseUrl:"/canvaskit/"},',
);
fs.writeFileSync(file, s);
console.log('patched: canvaskit now loads from /canvaskit/');
